import type { AssistantPageType, AssistantTopic } from "./types.ts";

export const assistantStopwords = new Set([
  "a",
  "about",
  "an",
  "and",
  "are",
  "as",
  "at",
  "be",
  "before",
  "between",
  "can",
  "do",
  "for",
  "from",
  "how",
  "i",
  "if",
  "in",
  "is",
  "it",
  "me",
  "my",
  "of",
  "on",
  "or",
  "should",
  "so",
  "tell",
  "that",
  "the",
  "them",
  "they",
  "this",
  "to",
  "what",
  "which",
  "who",
  "why",
  "with",
  "would",
]);

export const townAliases: Record<string, string> = {
  bir: "bir",
  "bir billing": "bir",
  billing: "bir",
  dharamshala: "dharamshala",
  mcleod: "mcleodganj",
  mcleodganj: "mcleodganj",
  "mc leod": "mcleodganj",
  "mc leodganj": "mcleodganj",
  mcleodgaj: "mcleodganj",
  naggar: "naggar",
  palampur: "palampur",
  shimla: "shimla",
  solan: "solan",
  manali: "manali",
  baijnath: "bir",
};

export const topicAliases: Record<string, AssistantTopic[]> = {
  "remote work": ["remote-work"],
  remote: ["remote-work"],
  coworking: ["remote-work", "community"],
  wifi: ["remote-work"],
  internet: ["remote-work"],
  family: ["family"],
  families: ["family"],
  kids: ["family"],
  school: ["family"],
  quiet: ["quiet"],
  calm: ["quiet"],
  peaceful: ["quiet"],
  access: ["access"],
  accessible: ["access"],
  airport: ["access"],
  road: ["access"],
  commute: ["access"],
  travel: ["access"],
  "long stay": ["long-stay"],
  "long-term": ["long-stay"],
  permanent: ["long-stay"],
  settle: ["moving", "long-stay"],
  move: ["moving"],
  moving: ["moving"],
  relocate: ["moving"],
  settling: ["moving"],
  trial: ["moving"],
  "first 30 days": ["moving"],
  social: ["social"],
  community: ["community", "social"],
  friends: ["community", "social"],
  lonely: ["community"],
  isolation: ["community"],
  beautiful: ["beauty"],
  beauty: ["beauty"],
  scenic: ["beauty"],
  atmosphere: ["beauty"],
  tourist: ["tourism"],
  tourism: ["tourism"],
  crowds: ["tourism"],
  food: ["food"],
  groceries: ["food"],
  delivery: ["food"],
  bakery: ["food"],
  protein: ["food"],
  water: ["water", "food"],
  "tap water": ["water", "food"],
  safety: ["safety"],
  women: ["safety"],
  "women safety": ["safety"],
  crime: ["safety"],
  healthcare: ["safety"],
  property: ["property"],
  lease: ["property"],
  legal: ["property"],
  section: ["property"],
  rent: ["cost", "property"],
  cost: ["cost"],
  budget: ["cost"],
  money: ["banking", "cost"],
  banking: ["banking"],
  bank: ["banking"],
  upi: ["banking"],
  forex: ["banking"],
  cash: ["banking"],
  power: ["power"],
  backup: ["power"],
  inverter: ["power"],
  heating: ["power"],
  outage: ["power"],
  method: ["method"],
  works: ["method"],
  appleville: ["method", "town-fit"],
  compare: ["town-fit"],
  best: ["town-fit"],
  fit: ["town-fit"],
  longer: ["long-stay"],
  longerstay: ["long-stay"],
};

export const topicToPageTypes: Record<AssistantTopic, AssistantPageType[]> = {
  "town-fit": ["town", "guide", "meta"],
  "remote-work": ["guide", "town"],
  family: ["guide", "town"],
  quiet: ["guide", "town"],
  access: ["town", "guide"],
  "long-stay": ["guide", "town", "resource"],
  social: ["town", "guide", "resource"],
  beauty: ["town", "guide"],
  tourism: ["town", "guide"],
  food: ["resource"],
  water: ["resource"],
  banking: ["resource"],
  community: ["resource", "guide"],
  safety: ["resource", "town"],
  property: ["resource"],
  power: ["resource"],
  moving: ["resource", "guide", "town"],
  cost: ["town", "resource"],
  method: ["method", "meta"],
};

export const knownDomainTerms = new Set([
  ...Object.keys(townAliases),
  ...Object.keys(topicAliases),
  "himachal",
  "town",
  "towns",
  "quiz",
  "guide",
  "guides",
  "compare",
]);
