import type {
  AssistantPageType,
  AssistantTopic,
  AssistantUserProfile,
} from "./types.ts";

export const assistantStopwords = new Set([
  "a",
  "about",
  "am",
  "an",
  "and",
  "are",
  "as",
  "at",
  "be",
  "before",
  "between",
  "can",
  "do",
  "for",
  "from",
  "how",
  "i",
  "if",
  "in",
  "is",
  "it",
  "me",
  "my",
  "of",
  "on",
  "or",
  "should",
  "so",
  "tell",
  "that",
  "the",
  "them",
  "they",
  "this",
  "to",
  "what",
  "which",
  "who",
  "why",
  "with",
  "would",
]);

export const townAliases: Record<string, string> = {
  bir: "bir",
  "bir billing": "bir",
  billing: "bir",
  dharamshala: "dharamshala",
  mcleod: "mcleodganj",
  mcleodganj: "mcleodganj",
  "mc leod": "mcleodganj",
  "mc leodganj": "mcleodganj",
  mcleodgaj: "mcleodganj",
  naggar: "naggar",
  palampur: "palampur",
  shimla: "shimla",
  solan: "solan",
  manali: "manali",
  baijnath: "bir",
};

export const topicAliases: Record<string, AssistantTopic[]> = {
  "remote work": ["remote-work"],
  remote: ["remote-work"],
  coworking: ["remote-work", "community"],
  wifi: ["remote-work"],
  internet: ["remote-work"],
  family: ["family"],
  families: ["family"],
  kids: ["family"],
  school: ["family"],
  quiet: ["quiet"],
  quieter: ["quiet"],
  calm: ["quiet"],
  peaceful: ["quiet"],
  access: ["access"],
  accessible: ["access"],
  airport: ["access"],
  road: ["access"],
  commute: ["access"],
  travel: ["access"],
  "long stay": ["long-stay"],
  "long-term": ["long-stay"],
  permanent: ["long-stay"],
  settle: ["moving", "long-stay"],
  settled: ["moving", "long-stay"],
  move: ["moving"],
  moving: ["moving"],
  relocate: ["moving"],
  settling: ["moving"],
  trial: ["moving"],
  "first 30 days": ["moving"],
  social: ["social"],
  community: ["community", "social"],
  friends: ["community", "social"],
  lonely: ["community"],
  loneliness: ["community"],
  isolation: ["community"],
  beautiful: ["beauty"],
  beauty: ["beauty"],
  scenic: ["beauty"],
  atmosphere: ["beauty"],
  tourist: ["tourism"],
  tourism: ["tourism"],
  crowds: ["tourism"],
  food: ["food"],
  groceries: ["food"],
  grocery: ["food"],
  delivery: ["food"],
  bakery: ["food"],
  bakeries: ["food"],
  sourdough: ["food"],
  protein: ["food"],
  dairy: ["food"],
  cheese: ["food"],
  milk: ["food"],
  water: ["water", "food"],
  "tap water": ["water", "food"],
  safety: ["safety"],
  women: ["safety"],
  woman: ["safety"],
  female: ["safety"],
  harassment: ["safety"],
  healthcare: ["safety"],
  clinic: ["safety"],
  property: ["property"],
  land: ["property"],
  apartment: ["property"],
  flat: ["property"],
  buy: ["property"],
  purchase: ["property"],
  lease: ["property"],
  legal: ["property"],
  ownership: ["property"],
  "section 118": ["property"],
  section: ["property"],
  rent: ["cost", "property"],
  cost: ["cost"],
  budget: ["cost"],
  money: ["banking", "cost"],
  banking: ["banking"],
  bank: ["banking"],
  account: ["banking"],
  upi: ["banking"],
  atm: ["banking"],
  cash: ["banking"],
  forex: ["banking"],
  remittance: ["banking"],
  power: ["power"],
  electricity: ["power"],
  backup: ["power"],
  inverter: ["power"],
  ups: ["power"],
  heating: ["power"],
  heater: ["power"],
  outage: ["power"],
  outages: ["power"],
  method: ["method"],
  works: ["method"],
  scoring: ["method"],
  appleville: ["method", "town-fit"],
  compare: ["town-fit"],
  best: ["town-fit"],
  fit: ["town-fit"],
  longer: ["long-stay"],
  longerstay: ["long-stay"],
};

export const topicToPageTypes: Record<AssistantTopic, AssistantPageType[]> = {
  "town-fit": ["town", "guide", "meta"],
  "remote-work": ["guide", "town"],
  family: ["guide", "town"],
  quiet: ["guide", "town"],
  access: ["town", "guide"],
  "long-stay": ["guide", "town", "resource"],
  social: ["town", "guide", "resource"],
  beauty: ["town", "guide"],
  tourism: ["town", "guide"],
  food: ["resource"],
  water: ["resource"],
  banking: ["resource"],
  community: ["resource", "guide"],
  safety: ["resource", "town"],
  property: ["resource"],
  power: ["resource"],
  moving: ["resource", "guide", "town"],
  cost: ["town", "resource"],
  method: ["method", "meta"],
};

export const buyerProfileAliases: Record<string, AssistantUserProfile> = {
  outsider: "out_of_state_indian",
  "out of state": "out_of_state_indian",
  "another state": "out_of_state_indian",
  nri: "nri_oci",
  oci: "nri_oci",
  "living abroad": "nri_oci",
  "overseas indian": "nri_oci",
  foreigner: "foreign_national",
  "foreign national": "foreign_national",
  "non indian": "foreign_national",
  llp: "company",
  company: "company",
  business: "company",
  "private limited": "company",
};

export const indianLocationAliases = new Set([
  "mumbai",
  "delhi",
  "new delhi",
  "bangalore",
  "bengaluru",
  "pune",
  "hyderabad",
  "chennai",
  "kolkata",
  "gurgaon",
  "gurugram",
  "noida",
  "ghaziabad",
  "faridabad",
  "jaipur",
  "ahmedabad",
  "surat",
  "lucknow",
  "chandigarh",
  "kerala",
  "punjab",
  "haryana",
  "uttar pradesh",
  "maharashtra",
  "karnataka",
  "gujarat",
  "rajasthan",
  "tamil nadu",
  "west bengal",
]);

export const knownDomainTerms = new Set([
  ...Object.keys(townAliases),
  ...Object.keys(topicAliases),
  ...Object.keys(buyerProfileAliases),
  "himachal",
  "town",
  "towns",
  "quiz",
  "guide",
  "guides",
  "compare",
]);
