import type {
  AssistantIntentKind,
  AssistantSubIntent,
  AssistantTopic,
} from "./types.ts";

export type AssistantAnticipationSeed = {
  id: string;
  domainKind: AssistantIntentKind;
  subIntent: AssistantSubIntent;
  focusTopics: AssistantTopic[];
  sourceKind: "doc" | "module" | "mixed";
  sourceLabel: string;
  livePathname: string | null;
  comparisonCapable: boolean;
  singleTownCapable: boolean;
  followUpCapable: boolean;
  requiredKeywords: string[];
  preferredKeywords: string[];
  hintKeywords: string[];
  questionPatterns: string[];
  sampleTemplates: string[];
  strictFallback: boolean;
};

export type AssistantAnticipationSourceConfig = {
  id: string;
  docs: string[];
  modules: string[];
  seeds: AssistantAnticipationSeed[];
};

const productDocs = {
  prd: "docs/product/PRD.md",
  sitemap: "docs/product/sitemap.md",
  food: "docs/product/Himachal Pradesh Food Scene Research.md",
  banking: "docs/product/Himachal Pradesh Financial Accessibility Guide.md",
  womenSafety: "docs/product/Himachal Women's Safety and Autonomy.md",
  towns: "docs/product/Himachal Pradesh Town Information Compilation.md",
  community: "docs/product/deep-research-report (4).md",
} as const;

const liveModules = {
  towns: "src/lib/towns.ts",
  guides: "src/lib/guides.ts",
  food: "src/lib/food.ts",
  banking: "src/lib/banking.ts",
  womenSafety: "src/lib/womens-safety.ts",
  community: "src/lib/community.ts",
  property: "src/lib/property-rules.ts",
  power: "src/lib/power-infra.ts",
  moving: "src/lib/playbook.ts",
  method: "src/lib/how-it-works.ts",
} as const;

export const assistantAnticipationSourceMap: AssistantAnticipationSourceConfig[] = [
  {
    id: "town-fit",
    docs: [productDocs.prd, productDocs.sitemap, productDocs.towns],
    modules: [liveModules.towns, liveModules.guides],
    seeds: [
      {
        id: "town-overview",
        domainKind: "town_fit",
        subIntent: "single_town",
        focusTopics: ["town-fit"],
        sourceKind: "mixed",
        sourceLabel: "Town profiles and editorial guides",
        livePathname: null,
        comparisonCapable: false,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["about", "like"],
        preferredKeywords: ["town", "tell me about", "what is", "how is"],
        hintKeywords: ["overview", "summary", "fit", "town", "base"],
        questionPatterns: [
          "tell me about",
          "what is it like",
          "what is",
          "how is",
          "what about",
        ],
        sampleTemplates: [
          "tell me about {town}",
          "what is {town} like",
          "how is {town} as a base",
        ],
        strictFallback: false,
      },
      {
        id: "town-ranking",
        domainKind: "comparison",
        subIntent: "ranking",
        focusTopics: ["town-fit"],
        sourceKind: "mixed",
        sourceLabel: "Town comparisons and shortlist guides",
        livePathname: null,
        comparisonCapable: true,
        singleTownCapable: false,
        followUpCapable: true,
        requiredKeywords: ["vs", "or", "against", "compare"],
        preferredKeywords: ["better", "rank", "stack up", "which town"],
        hintKeywords: ["compare", "shortlist", "choose", "fit", "tradeoff"],
        questionPatterns: [
          " vs ",
          " or ",
          "against",
          "compare",
          "better than",
          "rank it against",
          "stack up against",
        ],
        sampleTemplates: [
          "{townA} vs {townB}",
          "{townA} or {townB}",
          "tell me about {townA}. how would you rank it against {townB}?",
        ],
        strictFallback: false,
      },
      {
        id: "town-remote-work",
        domainKind: "comparison",
        subIntent: "ranking",
        focusTopics: ["town-fit", "remote-work"],
        sourceKind: "mixed",
        sourceLabel: "Remote-work town guidance",
        livePathname: null,
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["remote work", "work remotely", "internet"],
        preferredKeywords: ["wifi", "coworking", "workday"],
        hintKeywords: ["remote", "coworking", "digital", "internet"],
        questionPatterns: ["remote work", "work remotely", "coworking", "internet"],
        sampleTemplates: [
          "{townA} or {townB} for remote work",
          "which is better for remote work, {townA} or {townB}",
          "is {town} good for remote work",
        ],
        strictFallback: false,
      },
      {
        id: "town-family-fit",
        domainKind: "comparison",
        subIntent: "ranking",
        focusTopics: ["town-fit", "family"],
        sourceKind: "mixed",
        sourceLabel: "Family-fit town guidance",
        livePathname: null,
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["family", "families", "kids"],
        preferredKeywords: ["schools", "family life", "children"],
        hintKeywords: ["family", "schools", "routine", "children"],
        questionPatterns: ["for families", "family", "kids", "schools"],
        sampleTemplates: [
          "{townA} vs {townB} for families",
          "which town is better for family life, {townA} or {townB}",
          "is {town} good for families",
        ],
        strictFallback: false,
      },
      {
        id: "town-quiet-fit",
        domainKind: "comparison",
        subIntent: "ranking",
        focusTopics: ["town-fit", "quiet"],
        sourceKind: "mixed",
        sourceLabel: "Quiet vs social town guidance",
        livePathname: null,
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["quiet", "quieter", "calm"],
        preferredKeywords: ["social", "noise", "crowds"],
        hintKeywords: ["quiet", "social", "pace", "calm"],
        questionPatterns: ["quiet", "quieter", "calm", "social"],
        sampleTemplates: [
          "{townA} or {townB} if i want quiet",
          "which town is quieter, {townA} or {townB}",
          "is {town} quiet enough for a longer stay",
        ],
        strictFallback: false,
      },
      {
        id: "town-long-stay",
        domainKind: "comparison",
        subIntent: "ranking",
        focusTopics: ["town-fit", "long-stay"],
        sourceKind: "mixed",
        sourceLabel: "Long-stay fit guidance",
        livePathname: null,
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["long stay", "longer stay", "long term"],
        preferredKeywords: ["home base", "base", "settle"],
        hintKeywords: ["stay", "settle", "base", "routine"],
        questionPatterns: ["long stay", "longer stay", "long term", "home base"],
        sampleTemplates: [
          "{townA} or {townB} for a longer stay",
          "which town is better as a home base, {townA} or {townB}",
          "is {town} good for a long stay",
        ],
        strictFallback: false,
      },
    ],
  },
  {
    id: "food-water",
    docs: [productDocs.food, productDocs.sitemap],
    modules: [liveModules.food],
    seeds: [
      {
        id: "food-water-water",
        domainKind: "food_water",
        subIntent: "water",
        focusTopics: ["food", "water"],
        sourceKind: "mixed",
        sourceLabel: "Food reality in Himachal",
        livePathname: "/food",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["water", "tap water", "drinking water"],
        preferredKeywords: ["safe", "safe water", "water situation", "ro", "boil", "purify"],
        hintKeywords: ["water", "drinking", "purification", "hydrological", "ro"],
        questionPatterns: ["water situation", "tap water", "drinking water", "water safe"],
        sampleTemplates: [
          "tell me about water situation in {town}",
          "is tap water safe in {town}",
          "{townA} vs {townB} for water",
        ],
        strictFallback: true,
      },
      {
        id: "food-water-delivery",
        domainKind: "food_water",
        subIntent: "delivery",
        focusTopics: ["food"],
        sourceKind: "mixed",
        sourceLabel: "Food reality in Himachal",
        livePathname: "/food",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["delivery", "swiggy", "zomato", "deliver", "delivers"],
        preferredKeywords: ["food delivery", "home delivery", "app delivery"],
        hintKeywords: ["delivery", "swiggy", "zomato", "algorithmic"],
        questionPatterns: ["swiggy", "zomato", "food delivery", "deliver in", "delivers in"],
        sampleTemplates: [
          "does swiggy deliver in {town}",
          "zomato in {town}",
          "{townA} vs {townB} for delivery",
        ],
        strictFallback: true,
      },
      {
        id: "food-water-groceries",
        domainKind: "food_water",
        subIntent: "groceries",
        focusTopics: ["food"],
        sourceKind: "mixed",
        sourceLabel: "Food reality in Himachal",
        livePathname: "/food",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["groceries", "grocery", "protein", "dairy", "bakery"],
        preferredKeywords: ["market", "mandi", "milk", "cheese", "sourdough"],
        hintKeywords: ["markets", "protein", "dairy", "bakery", "grocery"],
        questionPatterns: ["groceries", "market", "protein", "dairy", "bakery"],
        sampleTemplates: [
          "tell me about groceries in {town}",
          "protein in {town}",
          "{townA} vs {townB} for groceries",
        ],
        strictFallback: true,
      },
    ],
  },
  {
    id: "banking",
    docs: [productDocs.banking, productDocs.sitemap],
    modules: [liveModules.banking],
    seeds: [
      {
        id: "banking-account",
        domainKind: "banking",
        subIntent: "account_opening",
        focusTopics: ["banking"],
        sourceKind: "mixed",
        sourceLabel: "Banking and money in Himachal",
        livePathname: "/banking",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["bank account", "open account", "account"],
        preferredKeywords: ["documents", "nri account", "proof of address", "banking"],
        hintKeywords: ["account", "documentation", "banking", "non resident"],
        questionPatterns: ["bank account", "open account", "proof of address", "nri account", "banking in"],
        sampleTemplates: [
          "can i open a bank account in {town}",
          "bank account in {town}",
          "tell me about banking in {town}",
          "{townA} vs {townB} for banking setup",
        ],
        strictFallback: true,
      },
      {
        id: "banking-cash-upi",
        domainKind: "banking",
        subIntent: "cash_upi",
        focusTopics: ["banking"],
        sourceKind: "mixed",
        sourceLabel: "Banking and money in Himachal",
        livePathname: "/banking",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["upi", "cash", "atm", "payment", "payments"],
        preferredKeywords: ["merchant", "digital payment", "card", "money"],
        hintKeywords: ["upi", "cash", "atm", "payments", "merchant"],
        questionPatterns: ["upi", "cash", "atm", "payment failure", "digital payment"],
        sampleTemplates: [
          "upi in {town}",
          "do i still need cash in {town}",
          "{townA} vs {townB} for bank access",
        ],
        strictFallback: true,
      },
      {
        id: "banking-forex",
        domainKind: "banking",
        subIntent: "forex",
        focusTopics: ["banking"],
        sourceKind: "mixed",
        sourceLabel: "Banking and money in Himachal",
        livePathname: "/banking",
        comparisonCapable: false,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["forex", "remittance", "western union"],
        preferredKeywords: ["exchange", "moneygram", "wire transfer"],
        hintKeywords: ["forex", "exchange", "remittances", "international"],
        questionPatterns: ["forex", "western union", "moneygram", "wire transfer"],
        sampleTemplates: [
          "forex in {town}",
          "western union in {town}",
          "how easy is remittance in {town}",
        ],
        strictFallback: true,
      },
    ],
  },
  {
    id: "women-safety",
    docs: [productDocs.womenSafety, productDocs.sitemap],
    modules: [liveModules.womenSafety],
    seeds: [
      {
        id: "women-safety-town",
        domainKind: "women_safety",
        subIntent: "town_safety",
        focusTopics: ["safety"],
        sourceKind: "mixed",
        sourceLabel: "Women's safety in Himachal",
        livePathname: "/womens-safety",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["safe for women", "women", "woman", "female", "safety"],
        preferredKeywords: ["solo woman", "harassment", "staring", "unsafe"],
        hintKeywords: ["women", "safety", "harassment", "autonomy"],
        questionPatterns: ["safe for women", "safety in", "women in", "solo woman"],
        sampleTemplates: [
          "is {town} safe for women",
          "tell me about safety in {town}",
          "{townA} vs {townB} for women",
        ],
        strictFallback: true,
      },
      {
        id: "women-safety-healthcare",
        domainKind: "women_safety",
        subIntent: "healthcare",
        focusTopics: ["safety"],
        sourceKind: "mixed",
        sourceLabel: "Women's safety in Himachal",
        livePathname: "/womens-safety",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["healthcare", "hospital", "clinic", "gynec", "pregnant"],
        preferredKeywords: ["maternity", "gynae", "obgyn"],
        hintKeywords: ["healthcare", "gynecological", "maternity", "clinic"],
        questionPatterns: ["healthcare for women", "gynec", "maternity", "hospital"],
        sampleTemplates: [
          "women's healthcare in {town}",
          "{townA} vs {townB} for women's healthcare",
          "is {town} okay for women's healthcare access",
        ],
        strictFallback: true,
      },
    ],
  },
  {
    id: "community",
    docs: [productDocs.community, productDocs.prd, productDocs.sitemap],
    modules: [liveModules.community],
    seeds: [
      {
        id: "community-social",
        domainKind: "community",
        subIntent: "social",
        focusTopics: ["community"],
        sourceKind: "mixed",
        sourceLabel: "Community and wellbeing in Himachal",
        livePathname: "/community",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["community", "social", "friends", "lonely", "loneliness", "isolation"],
        preferredKeywords: ["meet people", "social life", "support"],
        hintKeywords: ["community", "social", "isolation", "support"],
        questionPatterns: ["social life", "lonely", "isolation", "community"],
        sampleTemplates: [
          "community in {town}",
          "will i feel lonely in {town}",
          "{townA} vs {townB} for community",
        ],
        strictFallback: true,
      },
      {
        id: "community-coworking",
        domainKind: "community",
        subIntent: "coworking",
        focusTopics: ["community", "remote-work"],
        sourceKind: "mixed",
        sourceLabel: "Community and wellbeing in Himachal",
        livePathname: "/community",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["coworking", "coliving"],
        preferredKeywords: ["network", "nomad", "meet people"],
        hintKeywords: ["coworking", "coliving", "integration"],
        questionPatterns: ["coworking", "coliving", "meet people through coworking"],
        sampleTemplates: [
          "coworking in {town}",
          "{townA} vs {townB} for coworking community",
          "can i meet people through coworking in {town}",
        ],
        strictFallback: true,
      },
      {
        id: "community-mental-health",
        domainKind: "community",
        subIntent: "mental_health",
        focusTopics: ["community"],
        sourceKind: "mixed",
        sourceLabel: "Community and wellbeing in Himachal",
        livePathname: "/community",
        comparisonCapable: false,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["mental health", "therapy", "therapist", "counselling"],
        preferredKeywords: ["tele manas", "aa", "na", "support group"],
        hintKeywords: ["mental", "therapy", "counselling", "support"],
        questionPatterns: ["mental health", "therapy", "therapist", "tele manas"],
        sampleTemplates: [
          "mental health support in {town}",
          "therapy in {town}",
          "is there counselling support in {town}",
        ],
        strictFallback: true,
      },
    ],
  },
  {
    id: "property",
    docs: [productDocs.prd, productDocs.sitemap],
    modules: [liveModules.property],
    seeds: [
      {
        id: "property-eligibility",
        domainKind: "property",
        subIntent: "eligibility",
        focusTopics: ["property"],
        sourceKind: "module",
        sourceLabel: "Property rules in Himachal",
        livePathname: "/property-rules",
        comparisonCapable: false,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["property", "buy", "section 118", "outsider"],
        preferredKeywords: ["can i buy", "can outsiders buy", "eligibility", "from mumbai"],
        hintKeywords: ["property", "section 118", "buy", "eligibility"],
        questionPatterns: ["can i buy", "can outsiders buy", "section 118", "from mumbai"],
        sampleTemplates: [
          "can i buy in {town} if i am from mumbai",
          "property in {town}",
          "can outsiders buy property in himachal",
        ],
        strictFallback: true,
      },
      {
        id: "property-lease",
        domainKind: "property",
        subIntent: "lease",
        focusTopics: ["property"],
        sourceKind: "module",
        sourceLabel: "Property rules in Himachal",
        livePathname: "/property-rules",
        comparisonCapable: false,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["lease", "rent agreement", "registered lease"],
        preferredKeywords: ["long lease", "lease instead", "safe route"],
        hintKeywords: ["lease", "registered", "rent"],
        questionPatterns: ["lease instead", "registered lease", "long lease"],
        sampleTemplates: [
          "what about lease instead",
          "is a registered lease safer in {town}",
          "how does lease work in himachal",
        ],
        strictFallback: true,
      },
      {
        id: "property-risk",
        domainKind: "property",
        subIntent: "risk",
        focusTopics: ["property"],
        sourceKind: "module",
        sourceLabel: "Property rules in Himachal",
        livePathname: "/property-rules",
        comparisonCapable: false,
        singleTownCapable: false,
        followUpCapable: true,
        requiredKeywords: ["gpa", "poa", "scam", "risk"],
        preferredKeywords: ["workaround", "benami", "buy now permission later"],
        hintKeywords: ["gpa", "poa", "risk", "void"],
        questionPatterns: ["gpa sale", "poa", "buy now permission later", "property scam"],
        sampleTemplates: [
          "is gpa safe in himachal property deals",
          "poa property risk in himachal",
          "buy now permission later in himachal",
        ],
        strictFallback: true,
      },
    ],
  },
  {
    id: "power",
    docs: [productDocs.towns, productDocs.sitemap],
    modules: [liveModules.power],
    seeds: [
      {
        id: "power-outages",
        domainKind: "power",
        subIntent: "outages",
        focusTopics: ["power"],
        sourceKind: "mixed",
        sourceLabel: "Power backup and heating in Himachal",
        livePathname: "/power-backup",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["power", "power cut", "power cuts", "outage", "outages", "electricity"],
        preferredKeywords: ["blackout", "load shedding"],
        hintKeywords: ["power", "outage", "electricity", "heating"],
        questionPatterns: ["power cuts", "outages", "electricity", "power situation"],
        sampleTemplates: [
          "power cuts in {town}",
          "{townA} vs {townB} for power cuts",
          "how bad are outages in {town}",
        ],
        strictFallback: true,
      },
      {
        id: "power-backup",
        domainKind: "power",
        subIntent: "backup",
        focusTopics: ["power"],
        sourceKind: "mixed",
        sourceLabel: "Power backup and heating in Himachal",
        livePathname: "/power-backup",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["inverter", "ups", "backup", "battery"],
        preferredKeywords: ["do i need inverter", "solar"],
        hintKeywords: ["backup", "inverter", "ups", "solar"],
        questionPatterns: ["do i need inverter", "backup", "ups", "battery"],
        sampleTemplates: [
          "do i need inverter in {town}",
          "backup in {town}",
          "{townA} vs {townB} for backup needs",
        ],
        strictFallback: true,
      },
      {
        id: "power-heating",
        domainKind: "power",
        subIntent: "heating",
        focusTopics: ["power"],
        sourceKind: "mixed",
        sourceLabel: "Power backup and heating in Himachal",
        livePathname: "/power-backup",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["heating", "heater", "warm", "winter heating"],
        preferredKeywords: ["electric blanket", "bukhari", "radiator"],
        hintKeywords: ["heating", "heater", "winter", "blanket"],
        questionPatterns: ["heating", "heater", "winter heating", "how to stay warm"],
        sampleTemplates: [
          "heating in {town}",
          "{townA} vs {townB} for winter heating",
          "how should i handle heating in {town}",
        ],
        strictFallback: true,
      },
    ],
  },
  {
    id: "moving",
    docs: [productDocs.prd, productDocs.sitemap, productDocs.towns],
    modules: [liveModules.moving],
    seeds: [
      {
        id: "moving-settling",
        domainKind: "moving",
        subIntent: "settling",
        focusTopics: ["moving"],
        sourceKind: "mixed",
        sourceLabel: "First 30 days in Himachal",
        livePathname: "/first-30-days",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["first month", "first 30 days", "move", "moving", "settle"],
        preferredKeywords: ["trial move", "rental setup", "onboarding"],
        hintKeywords: ["move", "settle", "trial", "onboarding"],
        questionPatterns: ["first month", "first 30 days", "trial move", "rental setup"],
        sampleTemplates: [
          "first month in {town}",
          "tell me about moving to {town}",
          "{townA} vs {townB} for settling in",
        ],
        strictFallback: true,
      },
      {
        id: "moving-utilities",
        domainKind: "moving",
        subIntent: "utilities",
        focusTopics: ["moving", "power"],
        sourceKind: "mixed",
        sourceLabel: "First 30 days in Himachal",
        livePathname: "/first-30-days",
        comparisonCapable: true,
        singleTownCapable: true,
        followUpCapable: true,
        requiredKeywords: ["sim", "utilities", "broadband", "proof of address"],
        preferredKeywords: ["lpg", "water connection", "electricity transfer"],
        hintKeywords: ["utilities", "sim", "proof", "broadband"],
        questionPatterns: ["sim", "utilities", "proof of address", "broadband"],
        sampleTemplates: [
          "utilities in {town}",
          "how hard is sim setup in {town}",
          "{townA} vs {townB} for settling logistics",
        ],
        strictFallback: true,
      },
    ],
  },
  {
    id: "method",
    docs: [productDocs.prd, productDocs.sitemap],
    modules: [liveModules.method],
    seeds: [
      {
        id: "method-how-it-works",
        domainKind: "method",
        subIntent: "how_it_works",
        focusTopics: ["method"],
        sourceKind: "mixed",
        sourceLabel: "How Appleville works",
        livePathname: "/how-it-works",
        comparisonCapable: false,
        singleTownCapable: false,
        followUpCapable: true,
        requiredKeywords: ["how this works", "how appleville works", "how do you decide"],
        preferredKeywords: ["score", "scoring", "citation", "citations", "trust"],
        hintKeywords: ["works", "scores", "citations", "limits"],
        questionPatterns: ["how this works", "how do you decide", "how do you score", "citation logic"],
        sampleTemplates: [
          "how does appleville work",
          "how do you score towns",
          "why should i trust these citations",
        ],
        strictFallback: true,
      },
    ],
  },
];

export const assistantAnticipationFollowUpTemplates = [
  {
    seedPrompt: "Bir or Dharamshala for a longer stay?",
    prompt: "and for families?",
    expectedPrimaryIntentKind: "comparison",
    expectedFocusDomainKind: "town_fit",
  },
  {
    seedPrompt: "tell me about naggar",
    prompt: "what about palampur instead?",
    expectedPrimaryIntentKind: "town_fit",
    expectedFocusDomainKind: "town_fit",
  },
  {
    seedPrompt: "Can outsiders buy property in Himachal?",
    prompt: "what about lease instead?",
    expectedPrimaryIntentKind: "property",
    expectedFocusDomainKind: "property",
  },
  {
    seedPrompt: "tell me about water situation in Naggar",
    prompt: "what about delivery?",
    expectedPrimaryIntentKind: "food_water",
    expectedFocusDomainKind: "food_water",
  },
] as const;
